/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv` (hash: 49f5ce8a61567bee53ecc759a3cc2572)
interface __BaseEnv_CloudflareEnv {
	AI: Ai;
	ASSETS: Fetcher;
	NEXT_PUBLIC_APP_ENV: "production";
	NEXT_PUBLIC_SUPABASE_URL: "https://cpipjhbujhxqknkkvqnn.supabase.co";
	NEXT_PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwaXBqaGJ1amh4cWtua2t2cW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0MzQ5MTYsImV4cCI6MjEwNjAxMDkxNn0.eX9SbLhfPSMcPMQSKmcPze9MIm2jQwU39rBycWknv90";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_APP_ENV" | "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_ANON_KEY">> {}
}
